name: Build for dependabot

on:
  push:
    branches:
      - dependabot/**

permissions:
  contents: read
  packages: read

jobs:
  build-for-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn --immutable
      - run: yarn test
