name: Release @navikt/eslint-react

on:
  push:
    paths:
      - .github/workflows/release-eslint-react.yml
      - libs/eslint-react/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          cache: yarn

      - run: yarn --immutable

      - name: Publish package
        if: github.ref == 'refs/heads/main'
        run: |
          ./scripts/create-release.sh eslint-react
          ./scripts/set-version.sh eslint-react
          cd libs/eslint-react && yarn npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
