name: Build and publish

on:
  push:
    paths:
      - libs/legacy/**

jobs:
  build-and-publish:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn --immutable
      - run: yarn test
        working-directory: libs/legacy
      - name: Publish library
        if: github.ref == 'refs/heads/main'
        run: yarn npm publish
        working-directory: libs/legacy

  increment-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-and-publish]
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Setup github connection for auth
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: yarn version -i patch
        working-directory: libs/legacy
      - run: git add . && git commit -m "[skip ci] bump version (@navikt/eslint-config-teamsykmelding)" && git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
