name: Release @navikt/eslint-react

on:
  push:
    branches:
      - main
      - flat
    paths:
      - .github/workflows/release-eslint-react.yml
      - libs/eslint-react/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          cache: yarn

      - run: yarn --immutable

      - name: Publish package
        if: github.ref == 'refs/heads/main' && needs.should_release.outputs.skip == 'false'
        run: |
          ./scripts/libs/create-release.sh react-eslint
          ./scripts/libs/set-version.sh react-eslint
          cd libs/react-eslint && yarn npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
